### ISSUE TITLE
basic example

### ISSUE THREAD

**Issue by jeffersonroy** [grero/RippleTools.jl#8]
Hi, 
I saw a post you made to the Julia Discourse about RippleTools.  I have recently switch to using a Ripple system and also to Julia.  Avoiding pre-processing in Matlab would be great.  However, I can't seem to get RippleTools to work.  Do you have a simple example of loading a .ns2 or .ns5 file?  When I try 
`
using RippleTools

a = RippleTools.load("D:\\temp\\test.ns2")
`
I get ERROR: MethodError: no method matching load(::String)

Any help would be great.

Thank you,
-Jefferson

**Comment by grero** [comment]
Hi!
 Great that you found the package, and I'm sorry that is a bit rough around the edges currently. Basically, the load function expects a FileIO.File type (since I'm planning to incorporate this with the FileIO framework at some point. So, what you can do is

```julia
a = RippleTools.load(File(format"NSX", "D:\temp\test.ns2"))
```

which should load the file for you. The continuous data is a bit buried, I'm afraid, you but you can access the data matrix like this:

```julia
wideband_data = a.data.data
```
which will give return a matrix of type In16 with dimensions of number of recording channels times number of timepoints. 

Please don't hesitate to file other issues as you find them, I'm happy to make this package much more user friendly.

**Comment by grero** [comment]
Oops, didn't mean to close this : )

**Comment by jeffersonroy** [comment]
Hi,
Thank so much!  I can now load files.  I'll play around and let you know if I have any questions, issues, or enhancements.
